enable_experimental: true

listen:
  port: 4040

namespaces:
  - name: test
    format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
    source_files:
      - .behave-sandbox/access.log